[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --include=dev --no-audit --no-fund --cache /tmp/barberagency-npm-cache"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start -- -p $PORT"
