import { createHmac, timingSafeEqual } from "node:crypto";
export type JsonRecord = Record<string, unknown>;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const HASH=/^[0-9a-f]{64}$/;
export const isRecord=(v:unknown):v is JsonRecord=>Boolean(v)&&typeof v==="object"&&!Array.isArray(v);
const env=(n:string)=>{const v=process.env[n]?.trim();if(!v)throw new Error(`${n.toLowerCase()}_not_configured`);return v};
const integer=(v:unknown,n:string,zero=false)=>{if(typeof v!=="number"||!Number.isSafeInteger(v)||(zero?v<0:v<=0))throw new Error(`${n}_invalid`);return v};
const text=(v:unknown,n:string)=>{if(typeof v!=="string"||!v.trim())throw new Error(`${n}_invalid`);return v.trim()};
const timeoutMs=()=>Math.min(15000,Math.max(1000,Number(process.env.BILLING_HTTP_TIMEOUT_MS)||8000));
export async function fetchTimed(url:string,init:RequestInit){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs());try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}}
export async function readJsonBody(request:Request,max=4096):Promise<JsonRecord>{
 const ct=request.headers.get("content-type")?.split(";",1)[0].trim().toLowerCase();if(ct!=="application/json")throw new Error("content_type_invalid");
 const length=Number(request.headers.get("content-length")||0);if(length>max)throw new Error("body_too_large");
 const raw=await request.text();if(new TextEncoder().encode(raw).length>max)throw new Error("body_too_large");
 let parsed:unknown;try{parsed=JSON.parse(raw)}catch{throw new Error("body_invalid")}if(!isRecord(parsed))throw new Error("body_invalid");return parsed;
}
export function readBaSession(h:string){const m=h.match(/(?:^|;\s*)ba_session=([^;]+)/);return m?m[1]:""}
export function resolveSessionUserId(body:unknown):number|null{if(!isRecord(body))return null;const u=isRecord(body.user)?body.user:{};const d=isRecord(body.data)?body.data:{};for(const v of [body.user_id,body.usuario_id,body.id,u.id,d.user_id,d.usuario_id])if(typeof v==="number"&&Number.isSafeInteger(v)&&v>0)return v;return null}
export function purchaseIntentCorsHeaders(request:Request){const origin=request.headers.get("origin")||"";const allowed=new Set(["https://barberagency-barberagency.gymh5g.easypanel.host","http://localhost:3000",...(process.env.BILLING_PURCHASE_INTENTS_ALLOWED_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean)]);if(origin&&!allowed.has(origin))throw new Error("origin_not_allowed");return{"Access-Control-Allow-Origin":origin||"https://barberagency-barberagency.gymh5g.easypanel.host","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, X-Requested-With","Access-Control-Allow-Credentials":"true",Vary:"Origin"}}
export function requirePurchaseIntentOrigin(request:Request){const origin=request.headers.get("origin")||"";purchaseIntentCorsHeaders(request);if(!origin)throw new Error("origin_required");}
export function normalizeCreatePayload(b:JsonRecord){const c=text(b.purchase_context,"purchase_context");const v=integer(b.variation_id,"variation_id");const l=b.target_license_id==null?null:integer(b.target_license_id,"target_license_id");const k=text(b.idempotency_key,"idempotency_key");if(!["onboarding","renewal"].includes(c))throw new Error("purchase_context_invalid");if(![4225,4226,4227,4228].includes(v))throw new Error("variation_id_invalid");if(c==="onboarding"&&l!==null)throw new Error("onboarding_target_forbidden");if(c==="renewal"&&l===null)throw new Error("renewal_target_required");if(k.length>128)throw new Error("idempotency_key_invalid");return{purchaseContext:c,variationId:v,targetLicenseId:l,idempotencyKey:k}}
export async function resolveSession(request:Request){const token=readBaSession(request.headers.get("cookie")||"");if(!token)throw new Error("session_required");const response=await fetchTimed(env("SESSION_ME_ENDPOINT"),{method:"GET",headers:{Cookie:`ba_session=${token}`},cache:"no-store"});const body=await response.json().catch(()=>null);const userId=response.ok&&(!isRecord(body)||body.ok!==false)?resolveSessionUserId(body):null;if(!userId)throw new Error("session_invalid");return{userId}}
export function authorizeBridge(request:Request){const expected=Buffer.from(env("BILLING_PURCHASE_INTENTS_BRIDGE_TOKEN"));const auth=request.headers.get("authorization")||"";const supplied=Buffer.from(auth.startsWith("Bearer ")?auth.slice(7):"");if(expected.length!==supplied.length||!timingSafeEqual(expected,supplied))throw new Error("bridge_unauthorized")}
export function signIntentClaim(id:string){if(!UUID.test(id))throw new Error("purchase_intent_id_invalid");return createHmac("sha256",env("BILLING_PURCHASE_INTENTS_CLAIM_SECRET")).update(id).digest("base64url")}
export function verifyIntentClaim(id:unknown,claim:unknown){if(typeof id!=="string"||!UUID.test(id)||typeof claim!=="string")throw new Error("purchase_intent_claim_invalid");const a=Buffer.from(signIntentClaim(id));const b=Buffer.from(claim);if(a.length!==b.length||!timingSafeEqual(a,b))throw new Error("purchase_intent_claim_invalid");return id}
export async function callPurchaseIntentRpc(name:string,payload:JsonRecord,role:"checkout"|"ingest"="checkout"){const base=env("BILLING_PURCHASE_INTENTS_POSTGREST_URL").replace(/\/$/,"");const token=env(role==="checkout"?"BILLING_PURCHASE_INTENTS_CHECKOUT_TOKEN":"BILLING_PURCHASE_INTENTS_INGEST_TOKEN");const response=await fetchTimed(`${base}/rpc/${name}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,apikey:token},body:JSON.stringify(payload),cache:"no-store"});const raw=await response.json().catch(()=>null);const body=Array.isArray(raw)&&raw.length===1?raw[0]:raw;if(!response.ok||!isRecord(body))throw new Error(isRecord(body)&&typeof body.code==="string"?body.code:"purchase_intent_rpc_failed");return body}
export function validateAttachPayload(b:JsonRecord){const id=verifyIntentClaim(b.purchase_intent_id,b.purchase_intent_claim);const hash=text(b.cart_binding_hash,"cart_binding_hash");if(!HASH.test(hash))throw new Error("cart_binding_hash_invalid");return{id,hash}}
export function validateBindPayload(b:JsonRecord){const id=text(b.purchase_intent_id,"purchase_intent_id");if(!UUID.test(id))throw new Error("purchase_intent_id_invalid");const hash=text(b.cart_binding_hash,"cart_binding_hash");if(!HASH.test(hash))throw new Error("cart_binding_hash_invalid");return{id,hash,order:integer(b.woocommerce_order_id,"woocommerce_order_id"),item:integer(b.woocommerce_order_item_id,"woocommerce_order_item_id"),customer:integer(b.woocommerce_customer_id,"woocommerce_customer_id",true),product:integer(b.product_id,"product_id"),variation:integer(b.variation_id,"variation_id"),quantity:integer(b.quantity,"quantity"),term:text(b.billing_term,"billing_term"),amount:integer(b.amount_cents,"amount_cents"),currency:text(b.currency,"currency").toUpperCase()}}
export function validateCancelPayload(b:JsonRecord){const id=text(b.purchase_intent_id,"purchase_intent_id");if(!UUID.test(id))throw new Error("purchase_intent_id_invalid");const rawHash=b.cart_binding_hash==null?null:b.cart_binding_hash;const hash=rawHash==null?null:text(rawHash,"cart_binding_hash");if(hash!==null&&!HASH.test(hash))throw new Error("cart_binding_hash_invalid");const order=b.woocommerce_order_id==null?null:integer(b.woocommerce_order_id,"woocommerce_order_id");const reason=text(b.reason,"reason");if(!["bind_failed","woocommerce_order_cancelled","woocommerce_order_failed","cart_abandoned"].includes(reason))throw new Error("reason_invalid");if(hash===null&&order===null)verifyIntentClaim(b.purchase_intent_id,b.purchase_intent_claim);return{id,hash,order,reason}}
export function safeIntentResponse(i:JsonRecord,claim?:string){return{ok:true,purchase_intent_id:i.id,...(claim?{purchase_intent_claim:claim}:{}),purchase_context:i.purchase_context,product_id:i.product_id,variation_id:i.variation_id,term:i.billing_term,amount:i.amount_cents,currency:i.currency,status:i.status,expires_at:i.expires_at}}
